[profile.default]
gas_reports = ["OpenZeppelinFullMath", "PRBMathCommon", "SoladyFixedPointMathLib", "SolmateFixedPoint"]
# Compiler optimization options to use (use same as project)
optimizer = true                                              # enable or disable the solc optimizer
optimizer_runs = 10000                                        # the number of optimizer runs

# Turn on if you want to make use of shell commands via Solidity contracts
ffi = true                                                    # whether to enable ffi or not

# Other
verbosity = 3                                                 # the verbosity of tests (3 displays traces for failed tests)
evm_version = 'london'                                        # the evm version (by hardfork name)
auto_detect_solc = true                                       # enable auto-detection of the appropriate solc version to use
cache = true                                                  # whether to cache builds or not
force = false                                                 # whether to ignore the cache (clean build)

# Fuzz run options - adjust as needed for your fuzzing campaign
[fuzz]
runs = 90000                                         # the number of fuzz runs for tests
max_local_rejects = 90000                            # max number of individual inputs that may be rejected before the test aborts
max_test_rejects = 90000                           # max number of combined inputs that may be rejected before the test aborts


